### ISSUE TITLE
how's it determened whenever I'm afk or not?

### ISSUE THREAD

**Issue by Owyn** [SerenTera/afk-notify#3]
I minimized my game, then someone invited me to party, it called `notificationafk` function but I saw no pop-up - is it because not much time passed since I minimized the game? afk test for non-afk notiication works fine

**Comment by SerenTera** [comment]
yeah its tested whether the following packets is sent to server, which most likely indicates a user not being afk:
'C_CHAT',
'C_PLAYER_LOCATION',
'C_START_SKILL',
'C_WHISPER',
'S_LOAD_TOPO',

Unfortunately, I have no idea how to check window state to determine whether the game is minimized or not.

**Comment by Owyn** [comment]
hmm weird, I didn't move my character while game was minimized I think but it still doesn't proc...

some node stuff like https://github.com/CeQadrat/active-window can give the ability to check what window is active, not sure how worth it'd be requiring smth like that tho

**Comment by SerenTera** [comment]
Well I suppose i can switch over to using active-window and incorporate the necessary parts into the module itself so it wouldn't need to require it

**Comment by Owyn** [comment]
That'd be great, cuz many people alt-tab the game all the time while waiting everything
